name: flutter_famous_places
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.0-334.4.beta

dependencies:
  flutter:
    sdk: flutter
  infinite_scroll_pagination: ^4.1.0 
  go_router: ^14.6.1
  flutter_svg: ^2.0.7
  intl: any
  flutter_localizations:
    sdk: flutter
  graphql_flutter: ^5.2.0-beta.7
  flutter_riverpod: ^2.6.1
  google_fonts: ^6.2.1
  firebase_core: ^3.8.1
  firebase_auth: ^5.3.3
  google_sign_in: ^6.2.2
  flutter_secure_storage: ^9.2.2
  jwt_decode: ^0.3.1
  firebase_storage: ^12.3.7
  riverpod: ^2.6.1
  riverpod_annotation: ^2.6.1
  flutter_hooks: ^0.20.5
  shimmer: ^3.0.0
  connectivity_plus: ^6.1.0
  sqflite: ^2.4.1
  sqflite_common_ffi_web: ^0.4.5+4
  path: ^1.9.0
  internet_connection_checker: ^3.0.1
  internet_connection_checker_plus: ^2.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
    # a tool for running code generators
  build_runner:
  # the code generator
  riverpod_generator:
  # riverpod_lint makes it easier to work with Riverpod
  riverpod_lint:
  # import custom_lint too as riverpod_lint depends on it
  custom_lint:

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/icons/divers/
    - assets/icons/navigationBottom/offSelection/
    - assets/icons/navigationBottom/onSelection/
    - assets/icons/medias/
    - assets/images/
  generate: true
